spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        connection:
          release_mode: on_close
        dialect:
          storage-engine: innodb
          format_sql: true
        show_sql: true
        format_sql: true
  datasource:
    url: ${SPRING_DATASOURCE_BASE_URL:jdbc:mysql://localhost:3306/sample?serverTimezone=UTC&useCursors=false&sendStringParametersAsUnicode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false}
    username: ${SPRING_DATASOURCE_BASE_USERNAME:root}
    password: ${SPRING_DATASOURCE_BASE_PASSWORD:1q2w3e4r}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

server:
  port: 5001
  servlet:
    context-path: /java
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true